#! /usr/bin/env bash

# install node
# https://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi
# TODO check node version
if ! type "node" > /dev/null; then
  echo "installing nodejs"
  wget https://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-armv6l.tar.xz
  tar -xvf node-v6.9.4-linux-armv6l.tar.xz
  cd node-v6.9.4-linux-armv6l.tar.xz
  sudo cp -R * /usr/local/
  cd ..
  rm -rf node-v6.9.4-linux-armv6l.tar.xz
  rm -rf node-v6.9.4-linux-armv6l
fi

# install yarn
if ! type "yarn" > /dev/null; then
  echo "Installing yarn"
  cd /opt
  wget https://yarnpkg.com/latest.tar.gz
  tar zvxf latest.tar.gz
  cd dist
  sudo cp -R * /opt/yarn
  mv dist yarn
  
  # link
  sudo bash -c "echo 'export PATH=\"\$PATH:/opt/yarn/bin\"' >> /etc/profile"
  
  # cleanup
  rm latest.tar.gz
  # sudo npm install pm2 -g --unsafe-perm 
fi

# install pm2 nodejs process manager
# https://github.com/Unitech/pm2
if ! type "pm2" > /dev/null; then
  echo "Installing pm2"
  sudo yarn global add pm2 --prefix /usr/local
fi

# wally installation
echo "installing wally"
cd /opt
git clone https://github.com/muuki88/daylight.git
cd daylight

# TODO bundle frontend with webpack
yarn install --production
yarn run prod

# startOrRestart?
pm2 start server.js --name="mirror"

# save process list
pm2 save
pm2 startup

